<div class="login_head">
    <h2>Reservacion</h2>

    <p class="clear"></p>
</div>
<div class="login_body">
    <h3><?php echo $this->titulo ?></h3>
    <form method="post">
        <input type="hidden" name="guardar" value="1">
        <ul>            
            <li>
                <input type="submit" class="submit" value="Confirmar"> <a href="reserva/listar">Cancelar</a>
            </li>
        </ul>
    </form>
</div>  