<div class="login_head">
    <h2>Reserva</h2>
    <p class="clear"></p>
</div>
<div class="login_body">
    <h3><?php echo $this->titulo ?></h3>
    <?php if (isset($this->error)) : ?>
        <div class="error">
            <img src="<?php echo $this->_plantilla ?>img/error.png" alt="Error de formulario">
            <span>Se ha detectado los siguientes errores:</span>
            <?php for ($i = 0; $i < count($this->error); $i++) : ?>
                <br><?php echo $i + 1, '. ', $this->error[$i] ?>
            <?php endfor; ?>
        </div>
    <?php endif; ?>
    <form method="post">
        <input type="hidden" name="guardar" value="1">
        <input type="hidden" name="cancha_id" value="<?php echo $this->cancha_id ?>" id="cancha_id">
        <input type="hidden" name="usuario_id" value="1">
        <ul>
            <li>
                <label for="fecha">Fecha</label>
                <input type="text" class="in" name="fecha" id="fecha" required 
                       value="<?php echo isset($this->dato['fecha']) ? $this->dato['fecha'] : '' ?>">
                <div class="carga_calendar"></div>
            </li>
            <li class="horas">
            </li>
            <li>
                <input type="submit" class="submit" value="Enviar">
            </li>
        </ul>
    </form>
</div> 