<?php if (isset($this->paginar)):?>
<?php $paginar =  $this->paginar;?>
    <div id="paginacion">
        <a class="texto">Página <strong><?php echo $paginar['actual']; ?></strong> de <strong><?php echo $paginar['npaginas']; ?></strong></a>
        <?php if ($paginar['actual'] != 1): ?>
            <a href="<?php echo $paginar['url'], $paginar['actual'] - 1, $paginar['ancla'] ?>" class="link" title="Anterior">«</a>
        <?php endif; ?>
        <?php if ($paginar['desde'] >= 2): ?>
            <a href="<?php echo $paginar['url'], 1, ADMIN , $paginar['ancla']?>" class="link">1</a>
            <?php if ($paginar['desde'] > 2): ?>
                <a class="texto">...</a>
            <?php endif; ?>
        <?php endif; ?>
        <?php for ($i = $paginar['desde']; $i <= $paginar['hasta']; $i++):?>
            <?php if ($paginar['actual'] == $i): ?>
                <a class="actual"><?php echo $i; ?></a>
            <?php else: ?>
                <a href="<?php echo $paginar['url'], $i, $paginar['ancla'] ?>" class="link"><?php echo $i; ?></a>
            <?php endif; ?>
        <?php endfor;?>
        <?php if ($paginar['hasta'] <= $paginar['npaginas'] - 1): ?>
            <?php if ($paginar['hasta'] < $paginar['npaginas'] - 1): ?>
                <a class="texto">...</a>
            <?php endif; ?>
            <a href="<?php echo $paginar['url'], $paginar['npaginas'], $paginar['ancla'] ?>" class="link"><?php echo $paginar['npaginas']; ?></a>
        <?php endif; ?> 
        <?php if ($paginar['actual'] != $paginar['npaginas']): ?>
            <a href="<?php echo $paginar['url'], $paginar['actual'] + 1, $paginar['ancla'] ?>" class="link" title="Siguiente">»</a>
        <?php endif; ?>
    </div>
<?php endif; ?>