<?php if ($this->dato) : ?>
    <table class="tabla">
        <tr><th>Nombre</th><th>Ubicacion</th><th class="opc">Opción</th></tr>
                    <?php for ($i = 0; $i < count($this->dato); $i++) : ?>
                <tr>
                    <td><?php echo $this->dato[$i]['placa'] ?></td>
                    <td><?php echo $this->dato[$i]['capacidad'] ?></td>
                    <td><?php echo $this->dato[$i]['empl'] ?></td>
                <td>
                    <a href="bus/editar/<?php echo $this->dato[$i]['id'] ?>">
                        <img src="<?php echo $this->_plantilla ?>img/edit.png" title="Editar"></a> |
                    <a href="bus/eliminar/<?php echo $this->dato[$i]['id'] ?>">
                        <img src="<?php echo $this->_plantilla ?>img/delete.png" title="Eliminar"></a>
                </td>
            </tr>
        <?php endfor; ?>            
    </table>
<?php else: ?>
    <p>No hay registros</p>
<?php endif; ?>