<div class="login_head">
    <h2>Bus</h2>
    <ul class="opciones">
        <li><a href="cancha/listar">Listar</a></li>
        <li><a href="cancha/nuevo">Nuevo</a></li>
    </ul>
    <p class="clear"></p>
</div>
<div class="login_body">
    <h3><?php echo $this->titulo ?></h3>
    <form method="post">
        <input type="hidden" name="guardar" value="1">
        <ul>            
            <li>
                <input type="submit" class="submit" value="Confirmar"> <a href="cancha/listar">Cancelar</a>
            </li>
        </ul>
    </form>
</div>  