<div class="login_head">
    <h2>Cancha</h2>
    <p class="clear"></p>
</div>
<div class="login_body">
    <h3><?php echo $this->titulo ?></h3>
    <?php if (Sesion::get('_msg')) : ?>
        <div class="correcto">
            <img src="<?php echo $this->_plantilla ?>img/correcto.png" alt="Guadado correctamente">
            <?php
            echo Sesion::get('_msg');
            Sesion::matar('_msg');
            ?>
        </div>
    <?php endif; ?>
    <?php if ($this->dato) : ?>
        <table class="tabla">
            <tr><th>Nombre</th><th>Ubicacion</th><th>Caificacion</th><th class="opc3">Opción</th></tr>
                    <?php for ($i = 0; $i < count($this->dato); $i++) : ?>
                <tr>
                    <td><?php echo $this->dato[$i]['nombre'] ?></td>
                    <td><?php echo $this->dato[$i]['ubicacion'] ?></td>
                    <td><?php if ($this->dato[$i]['calificacion'] == 1):?> <?php echo "muy malo"?>
                        <?php elseif ($this->dato[$i]['calificacion'] == 2):?> <?php echo "Malo"?>
                        <?php elseif ($this->dato[$i]['calificacion'] == 3):?> <?php echo "Regular"?>
                        <?php elseif ($this->dato[$i]['calificacion'] == 4):?> <?php echo "Bueno"?>
                        <?php elseif ($this->dato[$i]['calificacion'] == 5):?> <?php echo "Muy bueno"?>
                        <?php else:  echo "Sin calificacion"?></td>
                        <?php endif; ?>
                    <td>
                        <a href="reserva/nueva/<?php echo $this->dato[$i]['id'] ?>">
                            <img src="<?php echo $this->_plantilla ?>img/res.jpg" title="Hacer reserva"></a>
                    </td>
                </tr>
            <?php endfor; ?>            
        </table>
        <?php if (isset($this->paginar)) : ?>
            <?php echo $this->paginar ?>
        <?php endif; ?>
    <?php else: ?>
        <p>No hay registros</p>
    <?php endif; ?>
</div>  